url: https://ilearn-ml.github.io/page/
baseurl: / # /agency-jekyll-theme/

# Site settings
title: AiLearn
email: ailearn@ethercourt.ml # abdoulayedoucoure.ammi@gmail.com
description: Prêt(e) à optimiser votre productivité ? Nos formations IA vous montrent comment. AiLearn est une entreprise innovante spécialisée dans la formation en intelligence artificielle (IA). Fondée en 2006, notre mission est de démocratiser l'accès à l'IA et d'aider les professionnels à tirer le meilleur parti de cette technologie révolutionnaire.


# Team names, titles and social links
people:
- name: Chatbot d'orientaion dédié à votre école
  pic: message-bot # download bots-brands-solid.svg 1
  position: Chatbot de base # Rédiger des offres d'emploi
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/c/33605861568 # https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Améliorer votre CV
  pic: message-bot # download bots-brands-solid.svg 1
  position: Disponible en Extension
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Présenter vos compétences pour des clients
  pic: message-bot # download bots-brands-solid.svg 1
  position: Disponible en Extension
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Vérifier votre éligibilité aux postes
  pic: message-bot # download bots-brands-solid.svg 1
  position: Disponible en Extension
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Rédiger des lettres de motivation
  pic: message-bot # download bots-brands-solid.svg 1
  position: Disponible en Extension
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Analyser votre CV
  pic: message-bot # download bots-brands-solid.svg 1
  position: Disponible en Extension
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Rédiger les courriers de prise de contact # avec vos candidats
  pic: message-bot # download bots-brands-solid.svg 1
  position: Disponible en Extension
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Faire des simulations d'entretien # avec vos candidats
  pic: message-bot # download bots-brands-solid.svg 1
  position: Disponible en Extension
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/


- name: Se former en Intelligence Artificielle
  pic: message-bot # download bots-brands-solid.svg 1
  position: Disponible en Extension
  social:
    - title: comments #book bots code
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-0SE50974Y0406773CM3HYRMQ # https://twitter.com/neohack22
    - title: code # amazon
      url: https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-8W838427MU507113HM3HYLXQ # https://amzn.eu/d/gXZF6bS
    - title: whatsapp
      url: https://wa.me/p/9089964124363229/33605861568 # https://wa.me/c/33605861568 https://www.linkedin.com/company/27132274/admin/products/ethercourt-les-relations-investisseurs-assist%C3%A9es-par-lintelligence-artificielle/



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
    # url: https://twitter.com/AmmiMarketic
  # - title: facebook
    # url: https://www.facebook.com/monjobconnect # https://www.facebook.com/ammimarketic
  # - title: linkedin
    # url: https://www.linkedin.com/showcase/ammi-marketic
  - title: github
    url:  https://github.com/iLearn-ML/
    

# Postal address (add as many lines as necessary)
address:
  - line: BKO
  - line: PAR

# Build settings
markdown: kramdown
permalink: pretty
